[build]
# enable a cache for crates between builds
rustc-wrapper = "sccache"
# since we only care for builds for our own machine, let's benefit from thise juicy modern cpu features
rustflags = [ "-C","target-cpu=native" ]

# let's have some fun with "omgz performance rice dat cake"
# aaand we get out of memory errors when building nu...
[profile.release]
# link time optimization is slow, but allows inter-crate analysis
# lto = "fat"

[target.x86_64-pc-windows-msvc]
# apparently, the LLVM linker is faster than others...
linker = "lld-link.exe"

[target.x86_64-unknown-linux-gnu]
rustflags = [
"-C", "link-arg=-fuse-ld=lld",
]
