[build]
# enable a cache for crates between builds
rustc-wrapper = "sccache"
# since we only care for builds for our own machine, let's benefit from thise juicy modern cpu features
rustflags = [ "-C","target-cpu=native" ]

# let's have some fun with "omgz performance rice dat cake"
[profile.release]
# link time optimization is slow, but allows inter-crate analysis
# similarly, crates get split into chunks while compiling in order to maximize throughput
# but we don't care about compile wall time here, only RAWR PERFF
# less chunks affors more opportunity for optimiziations

[target.x86_64-pc-windows-msvc]
# apparently, the LLVM linker is faster than others...
linker = "lld-link.exe"

[target.x86_64-unknown-linux-gnu]
rustflags = [
"-C", "link-arg=-fuse-ld=lld",
# "-C", "gcc-ld=lld",
# "-C", "linker=clang",
]
