[character]
success_symbol = ' (dimmed green)'
# does not work yet in nushell
error_symbol = ' (dimmed red)'

[directory]
style = 'bold purple'
truncation_symbol = '⋯ /'
home_symbol = '∽'
truncation_length = 5

[java]
style = 'yellow dimmed'

[git_status]
# too slow
disabled = true

[package]
style = "dimmed cyan"

[rust]
style = "dimmed cyan"

[zig]
style = "dimmed yellow"

[memory_usage]
disabled = false
format = "$symbol $ram_pct ($style)"
threshold = 50
symbol = ""
style = "dimmed gray"
