theme = "nugu"

[editor]
shell = ["nu", "--commands"]
true-color = true
mouse = true

line-number = "relative"
rulers = [81, 121, 141]

auto-completion = true
completion-trigger-len = 3
auto-info = true
auto-pairs = true
auto-format = true

idle-timeout = 200

scrolloff = 5
scroll-lines = 1

cursorline = true
color-modes = true
auto-save = true
bufferline = "always"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "selections",
  "position",
  "separator",
  "position-percentage",
]
center = [
  "file-name",
  "separator",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
right = ["diagnostics", "spacer", "spinner"]
separator = "·"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "─"
tabpad = "╴"
newline = "⏎"

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 2
