[[language]]
name = "nasm"
auto-format = true
language-servers = [{ name = "asm-lsp" }]

[[language]]
name = "xml"
auto-format = false
language-servers = [{ name = "lemminx" }]

[[language]]
name  = "java"
auto-format = false
language-servers = [{ name = "jdtls" }]

[language-server.asm-lsp]
command = "asm-lsp"

[language-server.lemminx]
command = "lemminx"
