[[language]]
name = "nasm"
language-servers = [{ name = "asm-lsp" }, { name  = "bufferls" }]

[[language]]
name = "xml"
language-servers = [{ name = "lemminx" }, { name  = "bufferls" }]

[[language]]
name = "toml"
language-servers = [{ name = "taplo" }, { name  = "bufferls" }]

[language-server.bufferls]
command = "buffer-language-server"

[language-server.asm-lsp]
command = "asm-lsp"

[language-server.lemminx]
command = "lemminx"

[language-server.taplo]
command = "taplo"
args = ["lsp", "stdio"]
