return function(Group, groups, colors, styles)
  Group.new(
    'LspDiagnosticsVirtualTextHint',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsSignWarning',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsSignInformation',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new('LspDiagnosticsSignHint', colors.normal, colors.none, styles.NONE)
  Group.new(
    'LspDiagnosticsFloatingHint',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new('LspDiagnosticsSignError', colors.normal, colors.none, styles.NONE)
  Group.new(
    'LspDiagnosticsDefaultWarning',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsDefaultError',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsFloatingError',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsFloatingWarning',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsFloatingInformation',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsUnderlineInformation',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsUnderlineHint',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsDefaultInformation',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsDefaultHint',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsUnderlineError',
    colors.normal,
    colors.none,
    styles.underline
  )
  Group.new(
    'LspDiagnosticsVirtualTextError',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsVirtualTextWarning',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsVirtualTextInformation',
    colors.normal,
    colors.none,
    styles.NONE
  )
  Group.new(
    'LspDiagnosticsUnderlineWarning',
    colors.normal,
    colors.none,
    styles.underline
  )
end
