return function(Group, groups, colors, styles)
	Group.new('LspDiagnosticsVirtualTextHint', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsSignWarning', colors.warning, colors.none, styles.NONE)
	Group.new('LspDiagnosticsSignInformation', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsSignHint', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsFloatingHint', colors.normal, colors.none, styles.underline)
	Group.new('LspDiagnosticsSignError', colors.error, colors.none, styles.NONE)
	Group.new('LspDiagnosticsDefaultWarning', colors.warning, colors.none, styles.NONE)
	Group.new('LspDiagnosticsDefaultError', groups.Error, groups.Error, groups.Error)
	Group.new('LspDiagnosticsFloatingError', colors.error, colors.none, styles.underline)
	Group.new('LspDiagnosticsFloatingWarning', colors.warning, colors.none, styles.underline)
	Group.new('LspDiagnosticsFloatingInformation', colors.normal, colors.none, styles.underline)
	Group.new('LspDiagnosticsUnderlineInformation', colors.normal, colors.none, styles.underline)
	Group.new('LspDiagnosticsUnderlineHint', colors.normal, colors.none, styles.underline)
	Group.new('LspDiagnosticsDefaultInformation', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsDefaultHint', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsUnderlineError', colors.error, colors.none, styles.underline)
	Group.new('LspDiagnosticsVirtualTextError', colors.error, colors.none, styles.NONE)
	Group.new('LspDiagnosticsVirtualTextWarning', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsVirtualTextInformation', colors.normal, colors.none, styles.NONE)
	Group.new('LspDiagnosticsUnderlineWarning', colors.normal, colors.none, styles.underline)
end
