return function(Group, groups, colors, styles)
	Group.new('TSString', colors.normal, colors.none, styles.bold + styles.italic)
	Group.new('TSStringEscape', groups.TSString, colors.accent_weak, groups.TSString)
	Group.new('TSStringRegex', groups.TSString, colors.accent_weak, groups.TSString)
	Group.new('TSStringSpecial', groups.TSString, colors.debug, groups.TSString)
	Group.new('TSConstBuiltin', groups.TSString, groups.TSString, groups.TSString)
	Group.new('TSNumber', groups.TSString, groups.TSString, groups.TSString)
	Group.new('TSBoolean', groups.TSString, groups.TSString, groups.TSString)
	Group.new('TSFloat', groups.TSString, groups.TSString, groups.TSString)
	Group.new('TSCharacter', groups.TSString, groups.TSString, groups.TSString)

	Group.new('TSKeyword', colors.minor, colors.none, styles.NONE)
	Group.new('TSKeywordFunction', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSKeywordOperator', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSKeywordReturn', groups.TSKeyword, groups.TSKeyword, styles.bold + styles.underline)
	Group.new('TSConditional', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSRepeat', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSLabel', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword + styles.bold)
	Group.new('TSException', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSFuncMacro', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)
	Group.new('TSInclude', groups.TSKeyword, groups.TSKeyword, groups.TSKeyword)

	Group.new('TSMethod', colors.normal, colors.none, styles.NONE)

	Group.new('TSPunctBracket', colors.minor, colors.none, styles.NONE)
	Group.new('TSPunctDelimiter', groups.TSPunctBracket, groups.TSPunctBracket, groups.TSPunctBracket)
	Group.new('TSPunctSpecial', groups.TSPunctBracket, groups.TSPunctBracket, groups.TSPunctBracket)
	Group.new('TSOperator', groups.TSPunctBracket, groups.TSPunctBracket, groups.TSPunctBracket)

	Group.new('TSVariable', colors.normal, colors.none, styles.NONE)

	Group.new('TSType', colors.normal, colors.none, styles.NONE)
	Group.new('TSTypeBuiltin', groups.TSType, groups.TSType, groups.TSType)

	Group.new('TSComment', colors.important, colors.none, styles.bold + styles.italic)

	Group.new('TSNote', colors.accent_strong, colors.none, styles.bold)

	Group.new('TSFunction', colors.normal, colors.none, styles.NONE)
	Group.new('TSConstant', colors.normal, colors.none, styles.NONE)
	Group.new('TSConstMacro', colors.normal, colors.none, styles.NONE)
	Group.new('TSFuncBuiltin', colors.normal, colors.none, styles.NONE)
	Group.new('TSStructure', colors.normal, colors.none, styles.NONE)
	Group.new('TSTagDelimiter', colors.normal, colors.none, styles.NONE)
	Group.new('TSError', colors.error, colors.none, styles.NONE)
	Group.new('TSField', colors.normal, colors.none, styles.NONE)
	Group.new('TSParameter', colors.normal, colors.none, styles.NONE)
	Group.new('TSProperty', colors.normal, colors.none, styles.NONE)

	Group.new('TSNone', colors.none, colors.none, styles.NONE)
	Group.new('TSParameterReference', colors.normal, colors.none, styles.NONE)
	Group.new('TSConstructor', colors.normal, colors.none, styles.NONE)
	Group.new('TSAnnotation', colors.normal, colors.none, styles.NONE)
	Group.new('TSAttribute', colors.normal, colors.none, styles.NONE)
	Group.new('TSNamespace', colors.normal, colors.none, styles.NONE)
	Group.new('TSSymbol', colors.normal, colors.none, styles.NONE)
	Group.new('TSText', colors.normal, colors.none, styles.NONE)
	Group.new('TSStrong', colors.normal, colors.none, styles.NONE)
	Group.new('TSEmphasis', colors.normal, colors.none, styles.NONE)
	Group.new('TSUnderline', colors.normal, colors.none, styles.underline)
	Group.new('TSStrike', colors.normal, colors.none, styles.NONE)
	Group.new('TSMath', colors.normal, colors.none, styles.NONE)
	Group.new('TSTextReference', colors.normal, colors.none, styles.NONE)
	Group.new('TSEnvironment', colors.normal, colors.none, styles.NONE)
	Group.new('TSEnvironmentName', colors.normal, colors.none, styles.NONE)
	Group.new('TSTitle', colors.normal, colors.none, styles.NONE)
	Group.new('TSLiteral', colors.normal, colors.none, styles.NONE)
	Group.new('TSURI', colors.normal, colors.none, styles.NONE)
	Group.new('TSWarning', colors.warning, colors.none, styles.NONE)
	Group.new('TSDanger', colors.debug, colors.none, styles.NONE)
	Group.new('TSTag', colors.normal, colors.none, styles.NONE)
	Group.new('TSTagAttribute', colors.normal, colors.none, styles.NONE)
	Group.new('TSPlaygroundFocus', colors.important, colors.none, styles.NONE)
	Group.new('TSQueryLinterError', colors.error, colors.none, styles.NONE)
	Group.new('TSPlaygroundLang', colors.normal, colors.none, styles.NONE)
end
