# Disable specific steps - same options as the command line flag
disable = ["tldr"]

assume_yes = true

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

[composer]
self_update = false

[git]
# Additional git repositories to pull
repos = ["/home/oli/Workspace/*"]

max_concurrency = 12

pull_predefined = false

# Arguments to pass Git when pulling Repositories
arguments = "--ff --rebase --autostash"

# Commands to run before anything
[pre_commands]
"00 - Create BTRFS snapshot" = "echo TODO"

# Custom commands
[commands]

# Updating my configuration files
"00 - Refresh Dotfiles" = "java ~/Workspace/dotfiles/bootstripper.java ~/Workspace/dotfiles"

# install tools from cargo, that are not already in path
# TODO: this could be annoying when setting up a machine first time?
"01 - Install Cargo Tools" = "nu ~/Workspace/dotfiles/tools/cargo-tools.nu"

# Leider scheint der eingebaute "tldr" step von topgrade nicht für meine Version von TLDR funktionieren
"03 - TLDR" = "tldr --update"

# Dateisystem-Indexer ix erfrischen
"03 - Indexa Update" = "ix --update"
