# Disable specific steps - same options as the command line flag
# Siehe command -> Windows
disable = ["tldr", "vim"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = ["~/Workspace"]

pull_predefined= false

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]

# Updateing my configuration files
"Refresh Dotfiles" = "java ~/Workspace/dotfiles/bootstripper.java ~/Workspace/dotfiles"

# Leider scheint der eingebaute "tldr" step von topgrade nicht für meine Version von TLDR funktionieren
"TLDR" = "tldr --update"

# Update NeoVim-Plugins
"NeoVim Plugins" = "echo 'Updating Plugins (packer) in headless neovim instance.' ; nvim  --headless '+PluginsSync' '+autocmd User PackerComplete :qa'"

# Dateisystem-Indexer ix erfrischen
"Indexa Update" = "ix --update"
