[misc]
# Disable specific steps - same options as the command line flag
# disable = ["system"]
disable = ["vim"]

assume_yes = true

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

[composer]
self_update = true

[git]
# Additional git repositories to pull
repos = ["C:/Users/okr/Workspaces/*/"]

max_concurrency = 12

pull_predefined = false

# Arguments to pass Git when pulling Repositories
# arguments = "--ff --rebase"

# Commands to run before anything
[pre_commands]
"01 - Winget Export" = "winget export --disable-interactivity --accept-source-agreements --output 'C:/Users/okr/Tools/winget_installed_apps.json' *> $null"

[commands]
"10 - Refresh dotfiles" = "java W:/dotfiles/bootstripper.java W:/dotfiles"
"20 - Install Cargo Tools" = "cd W:/dotfiles/tools ; java install.java"
"30 - Advantage-PM Client" = "nu X:/update_apm_client.nu"
"31 - MeMate" = "nu X:/update_memate.nu"
"40 - TLDR" = "tldr --update"
