# Disable specific steps - same options as the command line flag
disable = ["tldr"]

assume_yes = true

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = ["/home/oli/Workspace/*"]

max_concurrency = 12

pull_predefined= false

# Arguments to pass Git when pulling Repositories
arguments = "--ff --rebase --autostash"

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]

# Updating my configuration files
"Refresh Dotfiles" = "java ~/Workspace/dotfiles/bootstripper.java ~/Workspace/dotfiles"

# Leider scheint der eingebaute "tldr" step von topgrade nicht für meine Version von TLDR funktionieren
"TLDR" = "tldr --update"

# Dateisystem-Indexer ix erfrischen
"Indexa Update" = "ix --update"

# Update hx editor
"Update helix" = "cd ~/Workspace ; git clone -q https://github.com/helix-editor/helix ; cd helix ; git pull ; ln -s ~/Workspace/helix/runtime /home/oli/.config/helix/ ; cargo install --path helix-term ; hx --grammar fetch ; hx --grammar build"