[misc]
disable = ["vim"]
assume_yes = true
no_retry = true
set_title = true
display_time = true
cleanup = true

[composer]
self_update = false

[git]
repos = ["/home/oli/Source/*", "/home/oli/Notes"]
arguments = "--ff --rebase"
max_concurrency = 12
pull_predefined = false
