# Disable specific steps - same options as the command line flag
disable = ["tldr"]

assume_yes = true

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = ["W:/misc/*/"]

max_concurrency = 12

pull_predefined= false

# Arguments to pass Git when pulling Repositories
arguments = "--ff --rebase --autostash"

[windows]
enable_winget = true

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Refresh dotfiles" = "java W:/dotfiles/bootstripper.java W:/dotfiles"

# Leider scheint der eingebaute "tldr" step von topgrade nicht für meine Version von TLDR funktionieren
"TLDR" = "tldr --update"

# Diese Skripte beziehen APM und MeMate aus dem Transfer.
"Advantage-PM Client" = ". C:/Users/okr/Tools/update_apm_client.ps1"
"MeMate" = ". C:/USers/okr/Tools/update_memate.ps1"

# Dateisystem-Indexer ix erfrischen
"Indexa Update" = "ix --update"
