# Disable specific steps - same options as the command line flag
# Siehe command -> Windows
disable = ["tldr", "vim"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Do not set the terminal title
set_title = true

# Cleanup temporary or old files
cleanup = true

[git]
# Additional git repositories to pull
repos = ["W:/apm.web", "W:/misc/*/"]

pull_predefined= false

# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

# Commands to run before anything
#[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
"Refresh dotfiles" = "java W:/misc/dotfiles/bootstripper.java W:/misc/dotfiles"

# Leider scheint der eingebaute "tldr" step von topgrade nicht für meine Version von TLDR funktionieren
"TLDR" = "tldr --update"

# Diese Skripte beziehen APM und MeMate aus dem Transfer.
"Advantage-PM Client" = ". D:/Tools/update_apm_client.ps1"
"MeMate" = ". D:/Tools/update_memate.ps1"

# Force update of fresh nightly neovim
"NeoVim Nightly" = "scoop update --force neovim-nightly"

# Update NeoVim-Plugins
"NeoVim Plugins" = "Write-Host 'Updating Plugins (packer) in headless neovim instance.' ; nvim  --headless -c 'autocmd User PackerComplete quitall' -c 'PluginsSync'"

# Dateisystem-Indexer ix erfrischen
"Indexa Update" = "ix --update"
