inherits = "base16_default_light"

"ui.virtual.ruler" = { bg = "base01" }
"comment" = { fg = "base03", modifiers = ["italic", "bold"] }

[palette]
base00 = "#f2f2f2" # Default Background
base01 = "#dcdcdc" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#c2c2c2" # Selection Background
base03 = "#8a8a8a" # Comments, Invisibles, Line Highlighting
base04 = "#2e2e2e" # Dark Foreground (Used for status bars)
base05 = "#1a1a1a" # Default Foreground, Caret, Delimiters, Operators
base06 = "#050505" # Light Foreground (Not often used)
base07 = "#000000" # Light Background (Not often used)
base08 = "#8c3532" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
base09 = "#b45f31" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
base0A = "#b88e36" # Classes, Markup Bold, Search Text Background
base0B = "#6c782e" # Strings, Inherited Class, Markup Code, Diff Inserted
base0C = "#4d7474" # Support, Regular Expressions, Escape Characters, Markup Quotes
base0D = "#4b6988" # Functions, Methods, Attribute IDs, Headings
base0E = "#6c5b7b" # Keywords, Storage, Selector, Markup Italic, Diff Changed
base0F = "#5c4343" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
