inherits = "base16_terminal"

[palette]
black = "#252525"
white = "#ffffff"

gray = "#555555"
red = "#a55f5f"
green = "#5f875f"
yellow = "#af875f"
blue = "#5f87af"
magenta = "#875faf"
cyan = "#5f8787"

light-gray = "#b0b0b0"
light-red = "#ff8700"
light-green = "#87af5f"
light-yellow = "#ffd700"
light-blue = "#87afd7"
light-magenta = "#d70087"
light-cyan = "#87d7d7"
