return {
  require'bugabinga.lsp.clients.java',
  require'bugabinga.lsp.clients.lua',
  require'bugabinga.lsp.clients.json',
  require'bugabinga.lsp.clients.archlinux',
  require'bugabinga.lsp.clients.asm',
  require'bugabinga.lsp.clients.bash',
  require'bugabinga.lsp.clients.c',
  require'bugabinga.lsp.clients.graphviz',
  require'bugabinga.lsp.clients.markdown',
  require'bugabinga.lsp.clients.rust',
  require'bugabinga.lsp.clients.toml',
  require'bugabinga.lsp.clients.vim',
  require'bugabinga.lsp.clients.xml',
  require'bugabinga.lsp.clients.zig',
}
