complete_from_path = true
ctrlc_exit = false
filesize_format = "kib"
nonzero_exit_errors = true
rm_always_trash = true
table_mode = "light"
pivot_mode = "auto"
disable_table_indexes = false
completion_match_method = "case-insensitive"
prompt = "__zoxide_hook; starship prompt"
skip_welcome_message = true
startup = [
"zoxide init nushell --hook prompt | save zoxide.nu",
"source zoxide.nu",
  # loading of plugins in nu seems inconsistent.
  # the only get loaded in interactive nu session.
  # not for scripts and --commands.
  # see https://github.com/nushell/nushell/issues/3892
"nu plugin --load (build-string $nu.env.CARGO_HOME / bin)",
"source nurc",
]

[color_config]
primitive_int = "blue"
primitive_decimal = "blue"
primitive_filesize = "blue_dimmed"
primitive_string = "blue"
primitive_line = "yellow"
primitive_columnpath = "cyan"
primitive_pattern = "white"
primitive_boolean = "blue"
primitive_date = "blue_dimmed"
primitive_duration = "blue_dimmed"
primitive_range = "white_dimmed"
primitive_path = "white_bold"
primitive_binary = "cyan"
separator_color = "purple"
header_align = "left" # left|l, right|r, center|c
header_color = "purple"
header_bold = true
index_color = "purple_dimmed"
leading_trailing_space_bg = "purple_reverse"

[line_editor]
auto_add_history = true
color_mode = "enabled"
completion_type = "circular"
edit_mode = "emacs"
history_duplicates = "ignoreconsecutive"
tab_stop = 2

[textview]
colored_output = true
header = true
line_numbers = false
pager = "less"
paging_mode = "quitifonescreen"
tab_width = 2
true_color = true
use_italics = true
vcs_modification_markers = true
theme = "Nord"

[env]
STARSHIP_SHELL = "nushell"
EDITOR = "nvim"
BAT_THEME = "Nord"
_ZO_ECHO = 1
