return {
	toggle_on = '',
	toggle_off = '',
	diagnostic = '⊙',
	spelling = '󰓆',
	linenumber = '󰉻',
	linehighlight = '󰘤',
	modified = '',
	lock = '',
	file = '',
	newline = '␤',
	carriage_return = '␍',
	lsp = '',
	subversion = '🐢',
	vim = '',
	branch = '',
	git = '',
	diff_add = '',
	diff_remove = '',
	diff_change = '',
	folder = '',
	terminal = '',
	macro = '',
	lazy = '󰄻',
}

