set shell := ['nu', '--commands']

# List available recipes.
default:
	@just --list

# Format lua and toml files.
fmt:
	stylua --verify --num-threads 100 .
	taplo fmt

# Lint lua and toml files.
lint:
	selene --num-threads 100 .
	taplo lint

# Update neovim plugins via paq sync. Closes itself right after update.
update:
	nvim --headless -u NONE -i NONE --cmd "lua require('bugabinga.plugins.headless')"

profile_file := `$"startuptime/(sys | get host | get hostname)_(date now | date format '%Y_%m_%d_%H_%M_%S').txt"`

# Profile startuptime of neovim. Depends on vim-startuptime.
profile:
	vim-startuptime -vimpath nvim -count 100 -warmup 10 init.lua | save {{profile_file}}
	open {{profile_file}}
