set shell := ['nu', '--commands']

# List available recipes.
default:
	@just --list

# Format lua and toml files.
fmt:
	stylua --verify --num-threads 100 .
	taplo fmt

# Lint lua and toml files.
lint:
	selene --num-threads 100 .
	taplo lint

# delete all current neovim state, cache and other ephemeral data.
# does NOT delete the configs
nuke:
	rm -r (run-external --redirect-combine nvim  "--headless" "-n" "-R" +'lua = vim.fn.stdpath[[data]]' +:q  | lines | last)
	rm -r (run-external --redirect-combine nvim  "--headless" "-n" "-R" +'lua = vim.fn.stdpath[[cache]]' +:q  | lines | last)
	rm -r (run-external --redirect-combine nvim  "--headless" "-n" "-R" +'lua = vim.fn.stdpath[[state]]' +:q  | lines | last)
